packaging_format = 2

id = "ditto"
name = "Ditto"
description.en = "A fun, customizable Nostr client that puts you in control"
description.fr = "Un client Nostr amusant et personnalisable qui vous laisse le contrôle"
version = "2.37.3~ynh1"
maintainers = ["ditto_ynh contributors"]

[upstream]
license = "AGPL-3.0-only"
website = "https://ditto.pub"
code = "https://gitlab.com/soapbox-pub/ditto"

[integration]
yunohost = ">= 11.1.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = "not_relevant"
sso = "not_relevant"
disk = "400M"
ram.build = "1G"
ram.runtime = "1M"

[install]

    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/ditto"

    [install.init_main_permission]
    type = "group"
    default = "visitors"
    help = "Who should be allowed to access Ditto?"

[resources]

    [resources.sources.main]
    url = "https://gitlab.com/soapbox-pub/ditto/-/archive/v2.37.3/ditto-v2.37.3.tar.gz"
    sha256 = "4e5c67cbd1cb13fbbe3f24060c759aaf6de11a910e31948442705874bafe0d84"
    autoupdate.strategy = "latest_gitlab_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.nodejs]
    version = "22"

    [resources.permissions]
    main.url = "/"
