#!/bin/bash
set -eu

source /usr/share/yunohost/helpers

ynh_script_progression --message="Removing Ditto Nginx configuration..." --weight=1
ynh_config_remove_nginx

ynh_script_progression --message="Removing Ditto files..." --weight=1
ynh_safe_rm "$install_dir"

ynh_script_progression --message="Ditto removal complete" --last
